version: "3"
services:
  app1:
    image: ethereum/client-go
    entrypoint: /bin/sh
    tty: true
    volumes:
      - ./private_net:/geth
    ports:
      - 8545:8545 # http.portのデフォルト.MetaMask接続用
  app2:
    image: ethereum/client-go
    entrypoint: "/bin/sh"
    tty: true
    volumes:
      - ./private_net2:/geth
  app3:
    image: ethereum/client-go
    entrypoint: "/bin/sh"
    tty: true
    volumes:
      - ./private_net3:/geth
  app4:
    image: ethereum/client-go
    entrypoint: "/bin/sh"
    tty: true
    volumes:
      - ./private_net4:/geth
